sudo: false

language: erlang
otp_release:
   - 19.0

python:
  - 3.4

addons:
  apt:
    packages:
      - build-essential
      - dbus
      - libgnutls-dev
      - libglib2.0-0

install:
  - pip install -r test/dbus_client_SUITE_data/requirements.txt
  - "make"

script:
  - "make tests"

notifications:
  email:
    on_success: change
    on_failure: always
