sudo: false

language: erlang
otp_release:
   - 19.0

python:
  - 3.4

addons:
  apt:
    packages:
      - build-essential
      - dbus
      - libgnutls-dev
      - libglib2.0-0

install:
  - "wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py --user && pip install --user -r test/dbus_client_SUITE_data/requirements.txt"
  - "make"

script:
  #  - "make tests"
  - "make"

notifications:
  email:
    on_success: change
    on_failure: always
